import "~/styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "./Navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`font-sans ${inter.variable} m-auto flex justify-center border-x border-slate-200 bg-black md:max-w-2xl`}
        >
          <TRPCReactProvider cookies={cookies().toString()}>
            <div className="block">
              <Navbar />
            </div>
            <div>{children}</div>
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
